#!/bin/bash

set -eux

pacman -Q bird
pacman -Q exabgp
pacman -Q stayrtr

cd /root/birdplan || :
echo "Excuting in '$(pwd)'..."

ARGS=()
# Determine if we're skipping jobs or not
skip_jobs=
for arg in "$@"; do
    case $arg in
        --no-jobs)
            skip_jobs=1
            ;;
        *)
            ARGS+=("$arg")
            ;;
    esac
done

# Check if we're using jobs by checking if they being skipped
if [ -z "$skip_jobs" ]; then
    cpus=$(nproc)
    jobcount=$((cpus / 2))
    ARGS+=(--numprocesses="$jobcount" --dist=loadfile)
fi

#nice -n 20 tox run -e runtest --recreate -- "${ARGS[@]}"
nice -n 20 tox run -e runtest -- "${ARGS[@]}"