#!/bin/bash

pacman -Q bird
pacman -Q exabgp

cd /root/birdplan

ARGS=("$@")
if [ ${#ARGS[@]} -eq 0 ]; then
    ARGS=(--numprocesses=auto --dist=loadfile)
fi

echo "RUNNING: tox -- ${ARGS[@]}"
nice tox -- ${ARGS[@]}
