#!/usr/bin/python
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (c) 2020, AllWorldIT
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
import sys
import time

route_filename = sys.argv[1]
our_asn = sys.argv[2]
ipv = sys.argv[3]


aspath_re = re.compile(r"as-path \[")


with open(route_filename, "r") as route_file:
    while True:
        raw_route = route_file.readline().rstrip()
        if not raw_route:
            break

        route = re.sub(aspath_re, f"as-path [{our_asn} ", raw_route)

        if "::" in route:
            if ipv == "ipv6":
                sys.stdout.write(f"neighbor fc00:100::2 {route} next-hop fc00:100::1\n")
                sys.stdout.flush()
                exabgp_ack = sys.stdin.readline()

        elif ipv == "ipv4":
            sys.stdout.write(f"neighbor 100.64.0.2 {route} next-hop 100.64.0.1\n")
            sys.stdout.flush()
            exabgp_ack = sys.stdin.readline()

while True:
    time.sleep(10)
